apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-operator-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-operator-{{ .Values.ingressClass }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: "{{ .Values.ingressClass }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "gateway-operator-{{ .Values.ingressClass }}"
  template:
    metadata:
      labels:
        name: "gateway-operator-{{ .Values.ingressClass }}"
    spec:
      serviceAccountName: gateway-operator-{{ .Release.Namespace }}
      containers:
        - name: gateway-operator
          # Replace this with the built image name
          image: "{{ .Values.image.registry }}/system_containers/gateway-operator:v5.7.0"
          imagePullPolicy: Always
          env:
            - name: INGRESS_CLASS
              value: {{ .Values.ingressClass }}
            - name: GLOBALKONG_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: app.maintainer.namespace-of-operator
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
