apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgresql-cluster
    system/appName: postgresql-cluster
  name: postgresql-cluster
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tcp-port-0
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP
