{
 "title": "kong_monitoring_query_token",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "model总数 completion token总数 prompt token总数 consumer总数",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Count of Model Service",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (model) (kong_http_status{envId=\"kong\",model!=\"null\"}))"
    }
   ]
  },
  {
   "title": "Count of Completion Token",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kong_completion_tokens)" }
   ]
  },
  {
   "title": "Count of Prompt Token",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kong_prompt_tokens)" }
   ]
  },
  {
   "title": "Count of Client",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(consumer) (kong_total_tokens{model!=\"null\"}))"
    }
   ]
  },
  { "title": "网关token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "kong_completion_tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kong_completion_tokens{envId=\"kong\", apiId=\"snapshotapi-n85v0p1p\"}"
    }
   ]
  },
  {
   "title": "kong_prompt_tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "kong_prompt_tokens{envId=\"kong\", apiId=\"snapshotapi-n85v0p1p\"}"
    }
   ]
  },
  {
   "title": "kong_total_tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "kong_total_tokens{envId=\"kong\", apiId=\"snapshotapi-n85v0p1p\"}"
    }
   ]
  },
  { "title": "tokens by model/req", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "completion_token/req",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(model) (kong_completion_tokens))/(count(kong_latency_sum{type=\"upstream\"}))"
    }
   ]
  },
  {
   "title": "prompt_tokens/req",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(model) (kong_prompt_tokens))/(count(kong_latency_sum{type=\"upstream\"}))"
    }
   ]
  },
  { "title": "token use by model", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "completion token use by model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "avg by(model) (kong_completion_tokens)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(model) (kong_completion_tokens)"
    },
    {
     "expr": "min by(model) (kong_completion_tokens)"
    },
    {
     "expr": "max by(model) (kong_completion_tokens)"
    }
   ]
  },
  {
   "title": "prompt token use by model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "avg by(model) (kong_prompt_tokens)"
    },
    {
     "expr": "sum by(model) (kong_prompt_tokens)"
    },
    {
     "expr": "min by(model) (kong_prompt_tokens)"
    },
    {
     "expr": "max by(model) (kong_prompt_tokens)"
    }
   ]
  },
  {
   "title": "Kong添加的延迟、Kong中每个服务/路由的总请求时间和上游服务延迟",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "kong_latency_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "kong_latency_sum{envId=\"kong\"}"
    }
   ]
  },
  {
   "title": "kong_latency_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "kong_latency_count{envId=\"kong\"}"
    }
   ]
  },
  { "title": "服务/路由消耗的总带宽（以字节为单位）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "kong_bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "kong_bandwidth{envId=\"kong\"}"
    }
   ]
  },
  { "title": "网关响应http code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "kong_http_status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum by(apiId, code) (kong_http_status{envId=\"kong\"})"
    }
   ]
  }
 ]
}